services:
  - type: web
    name: eqy-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYPAL_ENV
        value: live
